### ISSUE TITLE
Documentação com problemas

### ISSUE THREAD

**Issue by rafaeljusto** [DeveloperCielo/Boas-praticas-de-ecommerce#1]
Na documentação de [Boas Práticas de E-Commerce](https://developercielo.github.io/Boas-praticas-de-ecommerce/#validação-dos-números-do-cartão) a explicação do algoritmo Luhn para a validação do digito verificador do cartão não aborda o caso quando o resto da divisão do 4º passo da zero, e consequentemente o resultado do 5º passo será 10. Nestas situações, conforme descrito no [Wikipedia](https://en.wikipedia.org/wiki/Luhn_algorithm) utilizamos o último digito do resultado do 5º passo, que no caso é zero.

Seria importante deixar mais clara a documentação quanto a este caso, pois tivemos problemas em nossa empresa, e provavelmente outros clientes da Cielo que implementem o algoritmo baseado nesta documentação também tenham.

**Comment by netojoaobatista** [comment]
O algorítimo é meramente descritivo; o propósito não é servir de referência para implementação, mas informar que a validação é feita através do algorítimo. O grande ponto é que a maioria das linguagens e tecnologias oferecem bibliotecas para essa validação; sabendo qual algorítimo é utilizado, basta adicionar a dependência em sua aplicação.

:D

**Comment by rafaeljusto** [comment]
Esta documentação foi passada pelo nosso contato comercial na Cielo. Mesmo sendo meramente descritiva deveria conter o algoritmo completo ou apontar para alguma documentação oficial.

**Comment by netojoaobatista** [comment]
A informação sobre o dígito de verificação foi adicionada ao guia de boas práticas.

:smile:

**Comment by rafaeljusto** [comment]
Obrigado!
